### ISSUE TITLE
Have a windows (metro) style too ? 

### ISSUE THREAD

**Issue by championswimmer** [connors/photon#70] opened 2015-11-16 15:00 UTC
Using photon makes creating GUI a breeze, BUT, it looks really out of place when running such an app on Windows/Linux. 

Any plans to support Windows themed UI elements ?

**Comment by Martinspire** [comment] 2015-11-18 09:39
+1, OSX-only seems like an odd choice for a desktop-theme

**Comment by iamdade** [comment] 2015-11-29 23:49
You can check milestone, it's planned for v1.0.0

**Comment by bitwombat** [comment] 2015-12-04 05:14
@championswimmer Are you talking about how Electron's menu is above the Photon header?  That struck me as odd too.  I guess you can do away with Electron's menu altogether (just not create one) and use toolbar-actions.

**Comment by kumarharsh** [comment] 2016-02-01 08:23
@bitwombat I think what he meant was that the Mac look doesn't look *at home* in Windows or Linux.

**Comment by connors** [comment] 2016-02-23 07:09
Dupe of #7

**Closed by connors** 2016-02-23 07:09 UTC
